### ISSUE TITLE
3.4: rm 2to3 throws no such file error

### ISSUE THREAD

**Issue by robjwells** [zoidbergwill/homebrew-python#3]
With the python34 formula on my system, [the line to remove the 2to3 directory](https://github.com/zoidbergwill/homebrew-python/blob/master/python34.rb#L166) throws the following error:

```
Error: No such file or directory - /usr/local/Cellar/python34/3.4.3/bin/2to3
```

If you comment out that line the installation proceeds as you'd expect.

None of the directory tree below Cellar exists.

The python3.3 formula has the line commented out. Oddly, the python3.5 formula has still has the line active but the installation worked fine for me, so I'm not sure exactly what the cause is.

**Comment by zoidyzoidzoid** [comment]
I think removing the line from the earlier Python 3 formulae makes the most sense.

I remember having issues with this, that's probably why I commented it out in the 3.3 formula, but I'll remove the lines from the Python 3.3 and 3.4 formulae.
