### ISSUE TITLE
Brew Tap not working any more

### ISSUE THREAD

**Issue by AnnaDamm** [zoidbergwill/homebrew-python#6]
When trying to tap, i get the following error: 

> ~: brew tap zoidbergwill/python
> ==> Tapping zoidbergwill/python
> Cloning into '/usr/local/Homebrew/Library/Taps/zoidbergwill/homebrew-python'...
> remote: Counting objects: 7, done.
> remote: Compressing objects: 100% (7/7), done.
> remote: Total 7 (delta 3), reused 3 (delta 0), pack-reused 0
> Unpacking objects: 100% (7/7), done.
> **Error: Invalid formula: /usr/local/Homebrew/Library/Taps/zoidbergwill/homebrew-python/python33.rb
> Calling Formula.sha1 is disabled!**
> Use Formula.sha256 instead.
> /usr/local/Homebrew/Library/Taps/zoidbergwill/homebrew-python/python33.rb:5:in `<class:Python33>'
> Please report this to the zoidbergwill/python tap!
> **Error: Cannot tap zoidbergwill/python: invalid syntax in tap!**

**Comment by zoidyzoidzoid** [comment]
Hi @Arany, thanks for this report.

I'll update them all when I get a chance and swap to `sha256` hashes.
